development:
  adapter: async

test:
  adapter: async

production:
  adapter: <%= SampleFauxpaasApp::Config.cable.adapter %>
  url: <%= SampleFauxpaasApp::Config.cable.url %>
  channel_prefix: <%= SampleFauxpaasApp::Config.cable.channel_prefix %>
